# Generated by Django 2.2.1 on 2019-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('description', models.TextField()),
                ('p182_conversion', models.DecimalField(decimal_places=16, max_digits=17)),
            ],
        ),
    ]
